name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Log Google Chrome version
        run: google-chrome --version

      - name: Initialize database
        run: |
          source venv/bin/activate
          pip install psycopg2-binary
          if [ ! -d "migrations" ]; then
            flask db init
            flask db migrate -m "Initial migration."
          fi
          flask db upgrade

      - name: Populate database
        run: |
          source venv/bin/activate
          python add_products.py

      - name: Start Flask application
        run: |
          source venv/bin/activate
          nohup flask run --host=0.0.0.0 &

      - name: Wait for Flask to be ready
        run: |
          for i in {1..30}; do
            if curl http://127.0.0.1:5000/; then
              break
            fi
            echo "Waiting for Flask app to start..."
            sleep 1
          done

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          source venv/bin/activate
          pytest tests --chromedriver-executable-path ./drivers/chromedriver.exe
